print("Tip Calculator - ver 1.0")
bill: float = float(input("Total bill: $"))
tip_amount: int = int(input("Tip amount (10, 12, 15): "))
people_amount: int = int(input("People amount to split: "))
result: float = (bill * (1 + tip_amount/100) / people_amount)
print(f"Each person should pay: ${str(result)}")
